title: Ke ZhiCheng's Homepage
page-top-title: Ke ZhiCheng
top-section-bg-text: Software Engineering
home-subtitle: Ke ZhiCheng&ensp;|&ensp;柯志丞
copyright-text: '&copy; Ke ZhiCheng 2022-2024. All Rights Reserved.'
